accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("profile/", views.profile, name="profile"),
    path("<str:tag>/", views.same_tag, name="sametag"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import logout

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("todos/", include("todos.urls")),
    path("accounts/", include("accounts.urls")),
    path("studies/", include("studies.urls")),
    path("social/", include("social_django.urls", namespace="social")),
    path("chat/", include("chat.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studies/urls.py
from django.urls import path
from . import views

app_name = "studies"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("create_todos/<int:study_pk>", views.create_todos, name="create_todos"),
    path(
        "detail/<int:study_pk>/<int:management_pk>",
        views.delete_todos,
        name="delete_todos",
    ),
    path("detail/<int:study_pk>", views.detail, name="detail"),
    path("detail/<int:study_pk>/delete", views.delete, name="delete"),
    path("detail/<int:study_pk>/update", views.update, name="update"),
    path("info/<int:study_pk>", views.info, name="info"),
    path("detail/<int:study_pk>/join", views.join, name="join"),
    path("detail/<int:study_pk>/<int:user_pk>/refusal", views.refusal, name="refusal"),
    path(
        "detail/<int:study_pk>/<int:user_pk>/accept_and_drive_out",
        views.accept_and_drive_out,
        name="accept_and_drive_out",
    ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from studies.models import Study
from django.contrib.auth.validators import UnicodeUsernameValidator

# Create your models here.
class User(AbstractUser):
    first_name = None
    last_name = None

    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        ('username'),
        max_length=14,
        unique=True,
        help_text= ('Required. 14 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': ("A user with that username already exists."),
        },
    )
    nickname = models.CharField(max_length=14, null=True, blank=True)
    image = ProcessedImageField(
        upload_to="images/",
        null=True,
        blank=True,
        processors=[ResizeToFill(150, 150)],
        format="JPEG",
        options={"quality": 80},
    )
    join_study = models.ManyToManyField(Study, related_name="joined_study")

accounts/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    PasswordChangeForm,
    UserChangeForm,
)
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "password1",
            "password2",
            "nickname",
            "email",
        ]


# 이름, 이메일, 주소 필드를 가져오려면
# 다중 상속을 할 수 밖에 없다.
class CustomUserChangeForm(PasswordChangeForm, UserChangeForm):

    # 데이터는 클라이언트로 부터 가져오지만
    # DB 에 저장하지 못한다.
    # MRO : Method Resolution Order 때문인듯 하다.
    # link : https://engineer-mole.tistory.com/196
    def save(self):
        user = super().save(commit=True)

        # MRO 에 따라서 해결되지 않은 필드는 수작업으로 저장한다.
        user.nickname = self.cleaned_data["nickname"]
        user.email = self.cleaned_data["email"]
        user.image = self.cleaned_data["image"]

        user.save()

        return self.user

    class Meta:
        model = get_user_model()
        fields = [
            "old_password",
            "new_password1",
            "new_password2",
            "nickname",
            "email",
            "image",
        ]

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    update_session_auth_hash,
)
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from todos.models import Todos, Tag
from accounts.models import User
import operator
from .decorator import login_message_required
from django.contrib import messages

# Create your views here.
# 회원가입
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            # 소셜 로그인 때문에 인증 백엔드가 중첩되어 지정을 해줘야함.
            # link : https://ghqls0210.tistory.com/49
            auth_login(
                request, user, backend="django.contrib.auth.backends.ModelBackend"
            )
            return redirect("todos:today")

    else:
        form = CustomUserCreationForm()

    context = {
        "form": form,
    }

    # 바꿔야 함!
    return render(request, "accounts/complete/accounts_form.html", context)


# 로그인
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            # 소셜 로그인 때문에 인증 백엔드가 중첩되어 지정을 해줘야함.
            # link : https://ghqls0210.tistory.com/49
            auth_login(
                request,
                form.get_user(),
                backend="django.contrib.auth.backends.ModelBackend",
            )

            return redirect("todos:today")
    else:
        form = AuthenticationForm(request)

    context = {
        "form": form,
    }
    # 바꿔야 함!
    return render(request, "main_index.html", context)


# 로그아웃
@login_required
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)

    # 바꿔야 함!
    return redirect("index")


# 회원탈퇴
@login_required
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    # 바꿔야 함!
    return redirect("index")


# 회원정보 수정
@login_message_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.user, request.POST, request.FILES)

        if request.POST.get("new_password1") != request.POST.get("new_password2"):
            messages.warning(request, "새로운 비밀번호가 일치하지 않습니다")
            return redirect("accounts:update")

        if form.is_valid():
            form.save()
            # 비밀번호가 변경되면 기존 세션과 회원 인증 정보가
            # 일치하지 않게 되기 때문에 새로운 password hash 로
            # 세션을 업데이트 해주는 메소드이다.
            update_session_auth_hash(request, form.user)

            # 바꿔야 함!
            return redirect("accounts:profile")
        else:
            messages.warning(request, "기존의 비밀번호가 맞지 않습니다")
            return redirect("accounts:update")
    else:
        form = CustomUserChangeForm(request.user)
    context = {
        "form": form,
    }

    # 바꿔야 함!
    return render(request, "accounts/working/accounts_update.html", context)


# 프로필
@login_required
def profile(request):
    you = request.user
    user = User.objects.get(pk=you.pk)

    # 지금껏 user 가 쓴 tag 를 몇번 썼는지, 그리고 몇번 썼는지 세어서 context 로 넘겨줌
    todo = Todos.objects.filter(user_id=user)
    tags = Tag.objects.filter(todo__in=todo)

    tag_count = {}
    for t in tags:
        if t.content in tag_count:
            tag_count[t.content] += 1
        else:
            tag_count[t.content] = 1

    sorted_tag = sorted(tag_count.items(), key=operator.itemgetter(1), reverse=True)
    sorted_tag = sorted_tag[:10]

    result = []
    for tt in sorted_tag:
        result.append({"content": tt[0], "count": tt[1]})

    joined_studies = []
    studies = user.join_study.all()
    for study in studies:
        if user in study.participated.all():
            joined_studies.append(study)

    if len(todo) != 0:
        percent = round(todo.filter(is_completed=True).count() / todo.count() * 100)
    else:
        percent = 0
    context = {
        "user": user,
        "todos": todo,
        "result": result,
        "joined_studies": joined_studies,
        "percent": percent,
    }
    return render(request, "accounts/working/mypage.html", context)


# 특정 태그의 Todo 목록
@login_required
def same_tag(request, tag):
    you = request.user
    user = User.objects.get(pk=you.pk)
    todo = Todos.objects.filter(user_id=user)
    same_tags = Tag.objects.filter(
        content=tag,
        todo__in=todo,
    )

    context = {"same_tags": same_tags, "tag": tag}

    return render(request, "accounts/working/same_tag.html", context)

templates/accounts/working/accounts_update.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container" id="user-update">
    <div class="box">
        <div class="logo">
            <img src="{% static 'img/planT_logo.svg' %}" alt="plan-t logo">
        </div>
        <h3 class="tit">회원정보 수정</h3>
        <form action="" method="POST" id="user-update-form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-area">
                <input type="text" name="nickname" maxlength="14" id="id_nickname" autofocus="autofocus">
                <label for="id_nickname">닉네임</label>
            </div>
            <div class="input-area">
                <input type="email" name="email" maxlength="254" id="id_email" autofocus="autofocus">
                <label for="id_email">이메일</label>
            </div>
            <div class="input-area">
                <input type="password" name="old_password" autocomplete="current-password" id="id_old_password" autofocus="autofocus">
                <label for="id_old_password">기존 비밀번호</label>
            </div>
            <div class="input-area">
                <input type="password" name="new_password1" autocomplete="new-password" id="id_new_password1" autofocus="autofocus">
                <label for="id_new_password1">새 비밀번호</label>
            </div>
            <div class="input-area">
                <input type="password" name="new_password2" autocomplete="new-password" id="id_new_password2" autofocus="autofocus">
                <label for="id_new_password2">새 비밀번호 확인</label>
            </div>
            <div class="input-area">
                <img src="" class="img-prev" width="100" height="100" height=alt="">
                <!-- <div class="loaded-file"></div>
                    <div class="upload-none">
                        <span class="attach_img-icon material-symbols-outlined">imagesmode</span>
                        사진/파일을 첨부하세요
                    </div> -->
                <input type="file" name="image" accept="image/*" id="image" autofocus="autofoucs">
                <label for="image" >프로필 이미지</label>
            </div>
            <button class="btn" type="submit">회원정보 수정하기</button>
        </form>
    </div>
    <script>
        // img 미리보기 기능
        const imageDOM = document.getElementById("image");
        const preview = document.querySelector(".img-prev");
        const imgLabel = document.querySelector("label[for='image']");

        preview.classList.remove("img-prev");
        preview.style.visibility = "hidden";

        imageDOM.addEventListener('change', () => {
            const reader = new FileReader();
            reader.onload = function(data) {
                preview.src = data.target.result;
            };
            preview.classList.add("img-prev");
            preview.style.visibility = "visible"
            reader.readAsDataURL(imageDOM.files[0]);
            imgLabel.innerText = "이미지 수정";
        });

        // input 태그에 데이터 추가
        let nickname = document.querySelector("#id_nickname");
        let email = document.querySelector("#id_email");
        let image = document.querySelector("#image");

        function SetInputTag(target, data) {
            if(data !== "None" && data !== ""){
                target.parentNode.classList.add("activate");
                return data;
            }
            else {
                target.parent.classList.remove("activate");
                return "";
            }
        }
        nickname.value = SetInputTag(nickname, "{{ request.user.nickname }}");
        email.value = SetInputTag(email, "{{ request.user.email }}");
    </script>
</div>
<!-- {{form}} -->

{% endblock body %}

templates/accounts/working/main_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="stylesheet" href="../../../static/styles/init.css">
    <link rel="stylesheet" href="../../../static/styles/accounts.css">
    <script src="../../../static/script/script.js" defer="defer"></script>
    <title>Document</title>
</head>

<body>
    <div id="main-login">
        <div class="container">
            <div class="slide">
                <img src="https://dummyimage.com/1000x600" alt="">
            </div>
            <div class="login">
                <div class="logo">
                    <img src="../../../static/img/planT_logo.svg" alt="plan-t logo">
                </div>
                <form action="" id="login-form" method="POST">
                    <div class="input-area">
                        <input type="text" name="username" id="id_username" autofocus="autofocus" />
                        <label for="username">아이디</label>
                    </div>
                    <div class="input-area">
                        <input type="password" name="password" id="id_password" />
                        <label for="password">비밀번호</label>
                    </div>
                    <button type="submit" class="btn">로그인</button>
                </form>
                <div class="link-area">
                    <a href="">회원가입</a>
                    <a href="">아이디/비밀번호 찾기</a>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

templates/accounts/working/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="box" id="mypage">
        <div class="user-info">
            <div class="profile-img">
                {% if user.image %}
                <img src="{{user.image.url}}" width="150" height="150" class="profimg" alt="프로필 이미지">
                {% else %}
                <img src="https://dummyimage.com/150x150" width="150" height="150" class="profimg" alt="프로필 이미지">
                {% endif %}
            </div>
            <a href="{% url 'accounts:update' %}" class="update-btn"><span class="material-symbols-outlined">
                    edit_square
                </span></a>
            <h2 class="tit">{{user.username}}</h2>
            {% if user.nickname %}
            <p class="nick">{{user.nickname}}</p>
            {% else %}
            <p class="nick">설정된 닉네임이 없습니다.</p>
            {% endif %}
        </div>
        <div class="todo-achieve">
            <h4 class="tit">TODO 달성률</h4>
            <p class="achieve-bg"></p>
            <p class="achieve-per" data-achieve-per="{{percent}}">
                <span class="achiever-num">0%</span>
            </p>
        </div>
        <div class="user-tag box">
            <h4 class="tit">많이 쓴 태그</h4>
            <div class="tag-area">
                {% for tag in result %}
                <a href="{% url 'accounts:sametag' tag.content %}" class="tag">
                    {{ tag.content }}
                    <span class="tag-count">{{ tag.count }}</span>
                </a>
                {% empty%}
                <span>아직 작성된 태그가 없어요 :( </span>
                {% endfor %}
            </div>

        </div>
        <div class="user-log box">
            <h4 class="tit">나의 스터디 현황</h4>
            <div class="user-study-area">
                {% for study in joined_studies %}
                <div class="box study-box">
                    <a href="{% url 'studies:detail' study.pk %}">
                        <p class="tit">{{ study.title }}</p>
                        <p class="desc">{{ study.desc }}</p>
                    </a>
                </div>
                {% empty%}
                <span>가입한 스터디가 없어요 :( </span>
                {% endfor %}
            </div>
        </div>

        <a href="{% url 'accounts:delete' %}" class="user-del-btn">탈퇴하기</a>
    </div>
</div>

{% endblock body %}

templates/accounts/working/same_tag.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="box" id="tag-list">
  <h3 class="tit"><span>#{{tag}}</span> 태그의 할일</h3>
  <p></p>
  {% for tag in same_tags %}
  <div class="box tag-box">
    <p class="tag-tit">{{ tag.todo.title }}</p>
    <p class="tag-cont">{{ tag.todo.content }}</p>
    <p class="tag-date">{{ tag.todo.when }}</p>
    <!-- <p>완료 :{{ tag.todo.is_completed }}</p> -->
  </div>
  {% endfor %}

  <!-- {% for tag in tags %}
  <div>{{ tag.content }}</div>
  {% endfor %} -->
</div>

{% endblock body %}

templates/accounts/working/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="stylesheet" href="../../../static/styles/init.css">
    <link rel="stylesheet" href="../../../static/styles/accounts.css">
    <script src="../../../static/script/script.js" defer="defer"></script>
    <title>Document</title>
</head>

<body>

    <div class="container" id="signup">
        <div class="box">
            <div class="logo">
                <img src="../../../static/img/planT_logo.svg" alt="plan-t logo">
            </div>
            <form action="" id="signup-form" method="POST">
                <div class="input-area">
                    <input type="text" name="username" id="id_username" autofocus="autofocus">
                    <label for="username">아이디</label>
                </div>
                <div class="input-area">
                    <input type="text" name="nickname" id="id_nickname" autofocus="autofocus">
                    <label for="nickname">닉네임</label>
                </div>
                <div class="input-area">
                    <input type="password" name="password1" id="id_password1">
                    <label for="password1">비밀번호</label>
                </div>
                <div class="input-area">
                    <input type="password" name="password2" id="id_password1">
                    <label for="password2">비밀번호 확인</label>
                </div>
                <div class="input-area">
                    <input type="email" name="email" id="id_email">
                    <label for="">이메일</label>
                </div>
                <button type="submit" class="btn">회원가입 하기</button>
            </form>
        </div>
    </div>
</body>

</html>