pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import logout

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("todos/", include("todos.urls")),
    path("accounts/", include("accounts.urls")),
    path("studies/", include("studies.urls")),
    path("social/", include("social_django.urls", namespace="social")),
    path("chat/", include("chat.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studies/urls.py
from django.urls import path
from . import views

app_name = "studies"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("create_todos/<int:study_pk>", views.create_todos, name="create_todos"),
    path(
        "detail/<int:study_pk>/<int:management_pk>",
        views.delete_todos,
        name="delete_todos",
    ),
    path("detail/<int:study_pk>", views.detail, name="detail"),
    path("detail/<int:study_pk>/delete", views.delete, name="delete"),
    path("detail/<int:study_pk>/update", views.update, name="update"),
    path("info/<int:study_pk>", views.info, name="info"),
    path("detail/<int:study_pk>/join", views.join, name="join"),
    path("detail/<int:study_pk>/<int:user_pk>/refusal", views.refusal, name="refusal"),
    path(
        "detail/<int:study_pk>/<int:user_pk>/accept_and_drive_out",
        views.accept_and_drive_out,
        name="accept_and_drive_out",
    ),
]

todos/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path("today/", views.today, name="today"),
    path("create/", views.create, name="create"),
    path("delete/<int:todos_pk>", views.delete, name="delete"),
    path("week/", views.week, name="week"),
    path("week/<str:few_week>", views.week_asyn, name="week_asyn"),
    path("read_all", views.read_all, name="read_all"),
    path("update/<int:pk>", views.update, name="update"),
    path("is_completed/", views.is_completed, name="is_completed"),
    path("detail_asyn/", views.detail_asyn, name="detail_asyn"),
]

studies/models.py
from django.db import models
from datetime import date, datetime
from django.conf import settings
from dateutil.relativedelta import relativedelta

# Create your models here.
now = datetime.now()


class Study(models.Model):
    category = models.CharField(max_length=10)
    title = models.CharField(max_length=50)
    desc = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    max_people = models.IntegerField()
    participated = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="participate"
    )
    start_at = models.DateField(default=str(now)[:10])  # 경고창이 떠서 now의 형식을 바꿈
    end_at = models.DateField(default=(now + relativedelta(months=6)))
    member_number = models.IntegerField(default=1)

    @property
    def is_activate(self):
        if self.end_at is None:
            return True
        else:
            return date.today() < self.end_date


class StudyTodos(models.Model):
    study_pk = models.ForeignKey("Study", on_delete=models.CASCADE)
    management_pk = models.ForeignKey("StudyTodosManagement", on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    content = models.TextField()
    start = models.DateField()
    end = models.DateField()
    is_completed = models.BooleanField(default=False)


class StudyTodosManagement(models.Model):
    pass

studies/forms.py
from django import forms
from .models import Study
from .models import StudyTodos


class StudyForm(forms.ModelForm):
    class Meta:
        model = Study
        fields = [
            "category",
            "title",
            "max_people",
            "desc",
        ]


class StudyTodosForm(forms.ModelForm):
    class Meta:
        model = StudyTodos
        fields = [
            "title",
            "content",
            "start",
            "end",
        ]

studies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Study, StudyTodos, StudyTodosManagement
from .forms import StudyForm, StudyTodosForm
from django.http import JsonResponse
from django.contrib.auth import get_user_model
from django.contrib import messages
from datetime import datetime
from django.contrib.auth.decorators import login_required
from accounts.decorator import login_message_required
from django.core.paginator import Paginator
from django.db.models import Q


# Create your views here.
# 스터디 목록
@login_required
def index(request):
    category = request.GET.get("tabmenu")

    # 카테고리
    if category is None or category == "on" or category == "None":
        category_studies = Study.objects.all().order_by("-pk")
    else:
        category_studies = Study.objects.filter(category=category).order_by("-pk")

    # 검색
    search = request.GET.get("search")
    if search is not None and search != "None":
        studies = Study.objects.all()
        search_lists = studies.filter(
            Q(title__icontains=search) | Q(desc__icontains=search)
        )
        category_studies = category_studies & search_lists
    # 페이지 네이션 코드
    page_number = request.GET.get("page")
    paginator = Paginator(category_studies, 8)
    page_list = paginator.get_page(page_number)

    context = {
        "category_studies": category_studies,
        "page_list": page_list,
        "category": category,
        "search": search,
    }

    return render(request, "studies/complete/study_index.html", context)


# 스터디 생성
@login_message_required
def create(request):
    if request.method == "POST":
        studyform = StudyForm(request.POST)
        # 시간저장(선택)
        start, end = (
            request.POST.get("start_at"),
            request.POST.get("end_at"),
        )

        if start <= end:
            if studyform.is_valid():
                form = studyform.save(commit=False)
                # 시간저장(선택)
                start, end = (
                    request.POST.get("start_at"),
                    request.POST.get("end_at"),
                )
                if start != "":
                    form.start_at = start
                if end != "":
                    form.end_at = end

                form.owner = request.user
                form.save()

                form.participated.add(request.user)
                request.user.join_study.add(form)
                return redirect("studies:index")
            # 필수 입력 사항을 빼먹을때
            messages.warning(request, "좀 더 자세히 입력해 주세요~")
            return redirect("studies:create")
        else:
            # 종료시점이 시작시점보다 먼저 있을 때
            messages.warning(request, "시작시점과 종료시점을 바르게 입력하세요")
            return redirect("studies:create")

    else:
        studyform = StudyForm()
    context = {"studyform": studyform}
    return render(request, "studies/complete/create_study.html", context)


@login_message_required
def update(request, study_pk):
    study_ = get_object_or_404(Study, pk=study_pk)

    if request.method == "POST":
        if request.user == study_.owner:
            studyform = StudyForm(request.POST, instance=study_)

            if studyform.is_valid():
                form = studyform.save(commit=False)
                # 시간저장(선택)
                start, end = (
                    request.POST.get("start_at"),
                    request.POST.get("end_at"),
                )
                form.start_at = start
                form.end_at = end
                form.save()
                return redirect("studies:detail", study_pk)
            else:
                messages.warning(request, "값이 잘못되었습니다.")
                return redirect("studies:detail", study_pk)
        else:
            messages.warning(request, "반장만 스터디를 바꿀 수 있습니다 ")
            return redirect("studies:detail", study_pk)
    else:
        studyform = StudyForm(instance=study_)
    # 날짜는 str로 바꾸어 줘야 value에서 받을 수 있다.
    study_start = str(study_.start_at)
    study_end = str(study_.end_at)

    context = {
        "studyform": studyform,
        "study": study_,
        "study_start": study_start,
        "study_end": study_end,
    }

    return render(request, "studies/complete/study_update.html", context)


# Study todo 생성
@login_message_required
def create_todos(request, study_pk):
    if request.method == "POST":
        study = Study.objects.get(pk=study_pk)
        study_todos_management = StudyTodosManagement.objects.create()
        start, end = request.POST.get("start"), request.POST.get("end")
        if start == "" and end != "":
            messages.error(request, "시작시점을 입력하세요.")
            return redirect("studies:detail", study_pk)
        elif start != "" and end == "":
            messages.error(request, "종료시점을 입력하세요.")
            return redirect("studies:detail", study_pk)
        elif start == "" and end == "":
            messages.error(request, "시작시점과 종료시점을 입력하세요.")
            return redirect("studies:detail", study_pk)
        else:
            pass
        # 가입된 멤버
        joined_member = []
        for user in study.participated.all():
            for studyy in user.join_study.all():
                if studyy.pk == study_pk:
                    joined_member.append(user)
                    break

        if start <= end:
            # 가입된 멤버 각각 생성
            for userr in joined_member:
                todoForm = StudyTodosForm(request.POST)

                if todoForm.is_valid() and study.owner == request.user:
                    todo = todoForm.save(commit=False)
                    todo.study_pk = study
                    todo.user_id = userr
                    todo.management_pk = study_todos_management
                    todo.save()
            else:
                return redirect("studies:detail", study_pk)
        else:
            messages.error(request, "올바른 기간을 입력해주세요.")
            return redirect("studies:detail", study_pk)

    messages.error(request, "저장 실패")
    return redirect("studies:detail", study_pk)


def delete_todos(request, study_pk, management_pk):
    management = get_object_or_404(StudyTodosManagement, pk=management_pk)
    study_ = get_object_or_404(Study, pk=study_pk)
    if request.user == study_.owner:
        if request.method == "POST":
            management.delete()
    return redirect("studies:detail", study_pk)


@login_required
def detail(request, study_pk):
    study_ = get_object_or_404(Study, pk=study_pk)
    # 인증
    if request.user in study_.participated.all():
        if study_ in request.user.join_study.all():
            # 로그인 유저, 시작은 오늘 이하, 끝은 오늘 이상의 study todos
            today = str(datetime.now())[:10]
            study_todos = StudyTodos.objects.filter(
                user_id=request.user,
                start__lte=today,
                end__gte=today,
                study_pk=study_,
            )
            #
            # 가입된 멤버
            joined_member = []
            # 수락은 안된 가입 신청 멤버
            application_member = []
            for user in study_.participated.all():
                for study in user.join_study.all():
                    if study.pk == study_pk:
                        joined_member.append(user)
                        break
                else:
                    application_member.append(user)
            #

            context = {
                "study": study_,
                "study_todo_form": StudyTodosForm(),
                "joined_member": joined_member,
                "application_member": application_member,
                "study_todos": study_todos,
            }

            return render(request, "studies/complete/study_detail.html", context)
    messages.error(request, "인증된 유저만 접근 할 수 있습니다.")
    return redirect("studies:index")


@login_required
def delete(request, study_pk):
    if request.method == "POST":
        study_ = get_object_or_404(Study, pk=study_pk)
        study_.delete()
        return redirect("studies:index")
    # 잘못된 방식으로 보내면
    return redirect("studies:detail", study_pk)


# study.participated.all
@login_required
def info(request, study_pk):
    study = get_object_or_404(Study, pk=study_pk)

    start = str(study.start_at)
    end = str(study.end_at)
    context = {
        "study": study,
        "study_todo_form": StudyTodosForm(),
        "start": start,
        "end": end,
    }

    return render(request, "studies/complete/study_info.html", context)


def join(request, study_pk):
    if request.method == "POST":
        study = get_object_or_404(Study, pk=study_pk)
        # 신청 취소
        if study.participated.filter(pk=request.user.pk).exists():
            study.participated.remove(request.user)
            is_participated = False
        # 가입신청
        else:
            study.participated.add(request.user)
            is_participated = True
        context = {
            "is_participated": is_participated,
        }
        return JsonResponse(context)
    else:
        messages.error(request, "잘못된 요청입니다.")
        return redirect("studies:index")


# 반장이 가입신청 인원 수락 거절(가입 신청기록 삭제)
def refusal(request, study_pk, user_pk):
    if request.method:
        study = get_object_or_404(Study, pk=study_pk)
        user = get_object_or_404(get_user_model(), pk=user_pk)
        # 오직 반장만 거절 가능
        if request.user == study.owner:
            study.participated.remove(user)
            studyJoinNumber = len(study.participated.all()) - 1
            context = {"studyJoinNumber": studyJoinNumber}
            return JsonResponse(context)

    messages.error(request, "잘못된 요청입니다.")
    return redirect("studies:index")


def accept_and_drive_out(request, user_pk, study_pk):
    if request.method == "POST":
        user = get_object_or_404(get_user_model(), pk=user_pk)
        study = get_object_or_404(Study, pk=study_pk)

        # 반장은 owner, 멤버는 not owner, 나쁜 사용자는 redirect
        if request.user == study.owner:
            owner__ = True
        elif request.user == user:

templates/studies/working/create_study.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>study update</title>
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
  <link rel="stylesheet" href="../../../static/styles/init.css">
  <link rel="stylesheet" href="../../../static/styles/study_form.css">
</head>

<body>

  <div class="container" id="create-study-area">
    <div class="box">
      <form action="" method="post" id="create-study-form">
        {% csrf_token %}
        <a href="./study_update.html" class="update-direct-icon">
          <span class="material-symbols-outlined">edit_note</span>
        </a>

        <!-- 스터디 title -->
        <label for="create-study-name"># 스터디 이름</label>
        <input type="text" name="title" value="" placeholder="" class="create-study-title" id="create-study-name">

        <!-- 스터디 category -->
        <fieldset class="study-create-categories">
          <legend># 카테고리</legend>
          <div class="categories-area">
            <input type="radio" name="category" id="ct0" value="생활" required>
            <label for="ct0">생활</label>
            <input type="radio" name="category" id="ct1" value="IT/개발">
            <label for="ct1">IT/개발</label>
            <input type="radio" name="category" id="ct2" value="외국어">
            <label for="ct2">외국어</label>
            <input type="radio" name="category" id="ct3" value="인문">
            <label for="ct3">인문</label>
            <input type="radio" name="category" id="ct4" value="수능">
            <label for="ct4">수능</label>
            <input type="radio" name="category" id="ct5" value="취업">
            <label for="ct5">취업</label>
            <input type="radio" name="category" id="ct6" value="면접">
            <label for="ct6">면접</label>
            <input type="radio" name="category" id="ct7" value="기타">
            <label for="ct7">기타</label>
          </div>
        </fieldset>

        <!-- 스터디 인원 -->
        <label for="study-members-num"># 스터디 인원</label>
        <input type="number" name="max_people" value="2" min="2" max="" id="study-members-num">

        <!-- 스터디 소개 -->
        <label for="study-info-text"># 스터디 소개</label>
        <textarea name="desc" id="study-info-text" cols="30" rows="10"></textarea>

        <!-- 시작일, 종료일-->
        <div class="study-datepicker">
          <fieldset class="study-start-picker">
            <legend># 시작일</legend>
            <input type="date" name="start_at" id="study-start-date">
          </fieldset>
          <fieldset class="study-end-picker">
            <legend># 종료일</legend>
            <input type="date" name="end_at" id="study-end-date">
          </fieldset>
        </div>

        <!-- 생성, 취소 버튼 -->
        <div class="study-btn-area">
          <input type="submit" value="생성" class="study-create-btn">
          <a href="./study_index.html" class="study-cancel-btn">취소</a>
        </div>
      </form>
    </div>
  </div>
  <script>
    function myFunction() {
      var x = document.getElementById("ct0").required;
    }
  </script>
</body>

</html>

templates/studies/working/study_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>study_detail</title>
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
  <link rel="stylesheet" href="../../../static/styles/init.css">
  <link rel="stylesheet" href="../../../static/styles/study_detail.css">
</head>

<body>

  <div class="container" id="study-todo-area">
    <div class="box">
      <section id="study-detail-area">
        <!-- 스터디 수정 버튼 -->
        <a href="./study_update.html" class="edit-direct-btn">
          <span class="edit-icon_img material-symbols-outlined">edit_note</span>
        </a>
        <!-- 스터디 title -->
        <label for="study-detail-name"># 스터디 이름</label>
        <input type="text" name="" value="Plan-T" class="study-detail-title" id="study-detail-name" disabled>
        <!-- 스터디 소개 -->
        <label for="study-detail-text"># 스터디 소개</label>
        <div class="study-content">
          <textarea name="" id="study-detail-text" cols="30" rows="10" disabled>스터디 장</textarea>
          <div class="leader-profileimg">
            <img
              src="https://scontent.cdnsnapwidget.com/vp/4aefafd3bee59d1d0fa2b29a59fc2bc5/5D7701C4/t51.2885-15/sh0.08/e35/s640x640/47690229_1430752333723397_2893005724802088960_n.jpg"
              alt="" width="55" height="55">
          </div>
        </div>
        <!-- 스터디 인원 -->
        <label for="study-members-num"># 스터디 인원</label>
        <div class="members-area" id="study-members-num">
          <div class="study-membernum">3명</div>
          <span>/</span>
          <div class="study-totalnum">5명</div>
        </div>
        <!-- 승이-->
        <ul class="approve-members">
          <li>
            <div class="approve-user-info">
              <!-- user profile img -->
              <img src="https://dummyimage.com/40x40/bab3ba/000000.jpg" alt="" class="study-detail-userimg">
              <!-- username -->
              <h6>dahlia</h6>
            </div>
            <div class="detail-btn-group">
              <!-- approval btn -->
              <form action="">
                <input type="submit" value="승인" class="approval-btn">
              </form>
              <!-- reject btn -->
              <form action="">
                <input type="submit" value="거절" class="reject-btn">
              </form>
            </div>
          </li>
        </ul>
      </section>

      <div class="study-task-add">
        <button class="icon-btn add-btn">
          <div class="add-icon"></div>
          <div class="btn-txt">할 일 추가하기</div>
        </button>
      </div>

      <section class="study-todo-section">
        <div class="study-task-add-spec">
          <!-- today todo Form -->
          <form action="{% url 'todos:create' %}" method="post" id="study-task-form" enctype="multipart/form-data">
            <!-- 시작일, 종료일-->
            <div class="datepicker-area">
              <div class="studytask-startpick">
                <input type="date" name="start_at" id="studytask-start">
              </div>
              <div class="studytask-endpick">
                <input type="date" name="end_at" id="studytask-end">
              </div>
            </div>
            <input type="text" name="title" placeholder="할일 추가하기" class="study_task-title">
            <textarea name="content" class="study_task-textarea" id="id_content" cols="30" rows="10"
              placeholder="할 일 상세"></textarea>
            <fieldset class="study-task-fileadd">
              <legend>Image/File</legend>
              <label for="study-task-imgfile">
                <div class="study-loaded-file"></div>
                <div class="study-upload-none">
                  <span class="attach_img-icon material-symbols-outlined">imagesmode</span>
                  사진/파일을 첨부하세요
                </div>
              </label>
              <input type="file" name="file" class="study_task-img" id="study-task-imgfile">
            </fieldset>
            <div class="btn-area">
              <div class="keyword-box">
                <input type="text" name="keyword" id="" placeholder="#keyword">
              </div>
              <button type="submit" class="btn">할일 추가</button>
            </div>
          </form>
        </div>
      </section>
    </div>
    <div class="box-area">
      <div class="box study-task-area">
        <ul class="study-task-list">
          <li class="task activate">
            <p class="task-cont">task</p>
            <input type="checkbox" name="task-chb1" id="task-chb1">
            <label for="task-chb1" class="task-chb"></label>
          </li>
          <li class="task">
            <p class="task-cont">task</p>
            <input type="checkbox" name="task-chb2" id="task-chb2">
            <label for="task-chb2" class="task-chb"></label>
          </li>
          <li class="task">
            <p class="task-cont">task</p>
            <input type="checkbox" name="task-chb3" id="task-chb3">
            <label for="task-chb3" class="task-chb"></label>
          </li>
        </ul>
      </div>
    </div>
  </div>
  </div>
  <script>
    let studyUploadFile = document.getElementById("study-task-imgfile");
    let studyLoadedFile = document.querySelector(".study-loaded-file")
    const studyNoneFile = document.querySelector(".study-upload-none")

    studyLoadedFile.style.display = "none";

    studyUploadFile.onchange = () => {
      studyNoneFile.style.display = "none";
      studyLoadedFile.style.display = "block";
      let uploadFileName = studyUploadFile.files[0].name;
      studyLoadedFile.innerText = `${uploadFileName}`;
    }
  </script>
  <script>
    try {
      const inputBox = document.getElementsByTagName('input');

      const loginActivate = function (e) {
        inputArea = e.target.closest('.input-area');
        if (!e.target.value == "") {
          inputArea.classList.add("activate");
        }
        else {
          inputArea.classList.remove("activate");
        }
      };
      for (let i = 0; i < inputBox.length; i++) {
        inputBox[i].addEventListener('keyup', loginActivate);
      }
    } catch { }

    try {
      let slideUp = (target, duration = 500) => {
        target.style.transitionProperty = "height, margin, padding";
        target.style.transitionDuration = duration + "ms";
        target.style.boxSizing = "border-box";
        target.style.height = target.offsetHeight + "px";
        target.offsetHeight;
        target.style.overflow = "hidden";
        target.style.height = 0;
        target.style.paddingTop = 0;
        target.style.paddingBottom = 0;
        target.style.marginTop = 0;
        target.style.marginBottom = 0;
        window.setTimeout(() => {
          target.style.display = "none";
          target.style.removeProperty("height");
          target.style.removeProperty("padding-top");
          target.style.removeProperty("padding-bottom");
          target.style.removeProperty("margin-top");
          target.style.removeProperty("margin-bottom");
          target.style.removeProperty("overflow");
          target.style.removeProperty("transition-duration");
          target.style.removeProperty("transition-property");
          //alert("!");
        }, duration);
      };

      let slideDown = (target, duration = 500) => {
        target.style.removeProperty("display");
        let display = window.getComputedStyle(target).display;

        if (display === "none") display = "block";

        target.style.display = display;
        let height = target.offsetHeight;
        target.style.overflow = "hidden";
        target.style.height = 0;
        target.style.paddingTop = 0;
        target.style.paddingBottom = 0;
        target.style.marginTop = 0;
        target.style.marginBottom = 0;
        target.offsetHeight;
        target.style.boxSizing = "border-box";
        target.style.transitionProperty = "height, margin, padding";
        target.style.transitionDuration = duration + "ms";
        target.style.height = height + "px";
        target.style.removeProperty("padding-top");
        target.style.removeProperty("padding-bottom");
        target.style.removeProperty("margin-top");
        target.style.removeProperty("margin-bottom");
        window.setTimeout(() => {
          target.style.removeProperty("height");
          target.style.removeProperty("overflow");
          target.style.removeProperty("transition-duration");
          target.style.removeProperty("transition-property");
        }, duration);
      };

      let slideToggle = (target, duration = 500) => {
        if (window.getComputedStyle(target).display === "none") {
          return slideDown(target, duration);
        } else {
          return slideUp(target, duration);
        }
      };

      // =====

      let speedAnimation = 400;
      let target = document.querySelector('.study-todo-section');

      let slideBtnClick = (cl, sl) =>
        document
          .querySelector(cl)
          .addEventListener("click", () => sl(target, speedAnimation));

      slideBtnClick(".add-btn", slideToggle);
    } catch { }
  </script>
</body>

</html>

templates/studies/working/study_info.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
  <link rel="stylesheet" href="../../../static/styles/init.css">
  <link rel="stylesheet" href="../../../static/styles/study_form.css">
</head>
<body>

  <div class="container">
    <div class="box">
      <article id="study-info-area">
        <!-- 스터디 title -->
        <label for="study-info-name"># 스터디 이름</label>
        <input type="text" name="{{study.title}}" value="Plan-T" class="study-info-title" id="study-info-name" disabled> 
      
        <!-- 스터디 category -->
        <fieldset class="study-info-categories">
          <legend># 카테고리</legend>
          <div class="categories-area">
            <input type="radio" name="ct" id="ct0" checked>
            <label for="ct0">생활</label>
            <input type="radio" name="ct" id="ct1">
            <label for="ct1">IT/개발</label>
            <input type="radio" name="ct" id="ct2">
            <label for="ct2">외국어</label>
            <input type="radio" name="ct" id="ct3">
            <label for="ct3">인문</label>
            <input type="radio" name="ct" id="ct4">
            <label for="ct4">수능</label>
            <input type="radio" name="ct" id="ct5">
            <label for="ct5">취업</label>
            <input type="radio" name="ct" id="ct6">
            <label for="ct6">면접</label>
            <input type="radio" name="ct" id="ct7">
            <label for="ct7">기타</label>
          </div>
        </fieldset>

        <!-- 스터디 인원 -->

        <label for="study-members-num"># 스터디 인원</label>
        <div class="members-area" id="study-members-num">
          <div class="study-membernum">{{study.member_number}}명</div>
          <span>/</span>
          <div class="study-totalnum">{{study.max_people}}명</div>
        </div>

        <!-- 스터디 장의 경우, 스터디 승인 받아주는 창 보여짐 -->
        <!--추후 디테일 페이지로 옮겨야됨 담당자: 성인-->
        {% if request.user == study.owner%}
          <ul class="approve-members">
            <h6></h6>
            {% for user in application_member%}
              <li>
                <div class="approve-user-info">
                  <!-- user profile img -->
                  {% if user.image %}
                    <img src="user.image.url" alt="" class="study-detail-userimg">
                  {% else %}
                    <img src="https://dummyimage.com/40x40/bab3ba/000000.jpg" alt="" class="study-detail-userimg">
                  {% endif %}
                  <!-- username -->
                  <h6>{{user.username}}</h6>
                </div>
                <div class="detail-btn-group">
                  <!-- approval btn -->
                  <form action="{% url 'studies:accept' study.pk user.pk%}">
                    <input type="submit" value="승인" class="approval-btn">
                  </form>
                  <!-- reject btn -->
                  <form action="{% url 'studies:refusal' study.pk user.pk%}">
                    <input type="submit" value="거절" class="reject-btn">
                  </form>
                </div>
              </li>
            {% endfor %}
          </ul>
        {% endif %}

        <!-- 스터디 소개 -->
        <label for="study-info-text"># 스터디 소개</label>
        <textarea name="" id="study-info-text" cols="30" rows="10" disabled="disabled">{{study.desc}}</textarea>
        <!-- 시작일, 종료일-->
        <div class="study-detail-datepicker">
          <fieldset class="study-start-picker">
            <legend># 시작일</legend>
            <input type="date" name="" value="{{start}}" id="study-start-date" disabled="disabled">
          </fieldset>
          <fieldset class="study-end-picker">
            <legend># 종료일</legend>
            <input type="date" name="" value="{{end}}" id="study-end-date" disabled="disabled">
          </fieldset>
        </div>

        <!-- 스터디 디테일 페이지 이동 (승인받은 회원만) -->
        <!-- 스터디 가입 -->
        {% if request.user != study.owner %}
          <a href="{% url 'studies:join' study.pk %}">가입(임시)</a>
        {% endif %}
        <!-- 스터디 삭제 (스터디 장에게만) -->
        <!-- 스터디 index로 다시 돌아가기 -->
        </article>
      </div>
    </div>

  </body>

</html>