accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("profile/", views.profile, name="profile"),
    path("<str:tag>/", views.same_tag, name="sametag"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import logout

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("todos/", include("todos.urls")),
    path("accounts/", include("accounts.urls")),
    path("studies/", include("studies.urls")),
    path("social/", include("social_django.urls", namespace="social")),
    path("chat/", include("chat.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studies/urls.py
from django.urls import path
from . import views

app_name = "studies"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("create_todos/<int:study_pk>", views.create_todos, name="create_todos"),
    path(
        "detail/<int:study_pk>/<int:management_pk>",
        views.delete_todos,
        name="delete_todos",
    ),
    path("detail/<int:study_pk>", views.detail, name="detail"),
    path("detail/<int:study_pk>/delete", views.delete, name="delete"),
    path("detail/<int:study_pk>/update", views.update, name="update"),
    path("info/<int:study_pk>", views.info, name="info"),
    path("detail/<int:study_pk>/join", views.join, name="join"),
    path("detail/<int:study_pk>/<int:user_pk>/refusal", views.refusal, name="refusal"),
    path(
        "detail/<int:study_pk>/<int:user_pk>/accept_and_drive_out",
        views.accept_and_drive_out,
        name="accept_and_drive_out",
    ),
]

todos/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path("today/", views.today, name="today"),
    path("create/", views.create, name="create"),
    path("delete/<int:todos_pk>", views.delete, name="delete"),
    path("week/", views.week, name="week"),
    path("week/<str:few_week>", views.week_asyn, name="week_asyn"),
    path("read_all", views.read_all, name="read_all"),
    path("update/<int:pk>", views.update, name="update"),
    path("is_completed/", views.is_completed, name="is_completed"),
    path("detail_asyn/", views.detail_asyn, name="detail_asyn"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- favicon -->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'styles/favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'styles/favicon/favicon-32x32.png'%}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'styles/favicon/favicon-16x16.png'%}">
  <link rel="manifest" href="{% static 'styles/favicon/site.webmanifest' %}">
  <meta name="msapplication-TileColor" content="#3cddaa">
  <meta name="msapplication-TileImage" content="{% static 'styles/favicon/ms-icon-144x144.png' %}">
  <meta name="theme-color" content="#3cddaa">
  <!-- google font icon -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
  <link rel="stylesheet" href="{% static 'styles/mk_charts.css' %}">
  <link rel="stylesheet" href="{% static 'styles/init.css' %}">
  <link rel="stylesheet" href="{% static 'styles/main.css' %}">
  <link rel="stylesheet" href="{% static 'styles/accounts.css' %}">
  <link rel="stylesheet" href="{% static 'styles/today.css' %}">
  <link rel="stylesheet" href="{% static 'styles/create_today.css' %}">
  <link rel="stylesheet" href="{% static 'styles/alltask.css' %}">
  <link rel="stylesheet" href="{% static 'styles/study_form.css' %}">
  <link rel="stylesheet" href="{% static 'styles/study_index.css' %}">
  <link rel="stylesheet" href="{% static 'styles/study_detail.css' %}">
  <link rel="stylesheet" href="{% static 'styles/mediaquery.css' %}">
  <link rel="stylesheet" href="{% static 'styles/chat.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="{% static 'script/mk_charts.js' %}" defer></script>
  <script src="{% static 'script/script.js' %}" defer></script>
  <title>Plan-T</title>
</head>

<body>
  <header id="header">
    <div class="container">
      <nav class="navi">
        <a href="{% url 'todos:today' %}" class="logo">
          <img src="{% static 'img/planT_logo.svg' %}" alt="Plant_logo">
        </a>
        <div class="gnb-area">
          <ul class="gnb tit">
            <li class="gnb-tab">
              <a href="{% url 'todos:today' %}">PLANNER</a>
            </li>
            <li>
              <span>/</span>
            </li>
            <li class="gnb-tab">
              <a href="{% url 'studies:index' %}">STUDY</a>
            </li>
          </ul>
        </div>
        {% if request.user.is_authenticated %}
        <div class="user-area">
          <div class="user-prof">
            {% if request.user.image %}
            <img src="{{ request.user.image.url }}" width="30" height="30" alt="">
            {% else %}
            <img src="https://dummyimage.com/30x30" alt="">
            {% endif %}
          </div>
          <a href="{% url 'accounts:profile' %}" class="username">
            {{request.user}}
          </a>
          <a href="{% url 'accounts:logout' %}" class="logout-btn">
            <span class="material-symbols-outlined">
              logout
            </span>
          </a>
        </div>
        {% endif %}
      </nav>
    </div>
  </header>
  <main id="main">
    <div class="container">
      {% block body %}{% endblock body %}
    </div>
  </main>
  <footer>
    <div class="cpr">
      <p>
        &copy; Plan-T 2022
      </p>
    </div>
  </footer>
  
  {% if messages %}
  {% for message in messages %}
    <div class="box" id="message-card">
      <h6 class="message-header"><span class="noti-icon material-symbols-outlined">notifications_active</span>오류 알림</h6>
      <h1 class="message-text">{{ message.message }}</h1>
      <button class="message-button" type="button">확인</button>
    </div>
  {% endfor %}
  {% endif %}
  {% block js %}{% endblock js %}

  <script>
    message = document.querySelectorAll('.message-button')
    console.log(message)
    message.forEach(function (v, i, o) {
      v.addEventListener('click', event => {
        v.parentElement.remove()
      })
    })
  </script>
</body>

</html>

templates/main_index.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'styles/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'styles/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'styles/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'styles/favicon/site.webmanifest' %}">
    <meta name="msapplication-TileColor" content="#3cddaa">
    <meta name="msapplication-TileImage" content="{% static 'styles/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#3cddaa">
    <!-- bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <!-- google font icon -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"/>
    <link rel="stylesheet" href="{% static 'styles/init.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'styles/accounts.css' %}">
    <link rel="stylesheet" href="{% static 'styles/mediaquery.css' %}">
    <script src="{% static 'script/script.js' %}" defer="defer"></script>
    <title>Plan-T</title>
  </head>

  <body>
    <div id="main-login">
      <div class="container">
        <div class="slide-area">
          <div class="slide slide--1">
            <img src="{% static 'img/slide01.jpg' %}" alt="main slide banner 01">
          </div>
          <div class="slide slide--2">
            <img src="{% static 'img/slide02.jpg' %}" alt="main slide banner 02">
          </div>
          <div class="slide slide--3">
            <img src="{% static 'img/slide03.jpg' %}" alt="main slide banner 03">
          </div>
          <div class="slide slide--4">
            <img src="{% static 'img/slide04.jpg' %}" alt="main slide banner 04">
          </div>
          <button class="slider-btn slider-btn-left">
            <span class="material-symbols-outlined">
              chevron_left
            </span>
          </button>
          <button class="slider-btn slider-btn-right">
            <span class="material-symbols-outlined">
              chevron_right
            </span>
          </button>
          <div class="dots"></div>

        </div>
        <div class="login">
          <div class="logo">
            <img src="{% static 'img/planT_logo.svg' %}" alt="plan-t logo">
          </div>
          <form action="{% url 'accounts:login' %}" id="login-form" method="POST">
            {% csrf_token %}
            <div class="input-area">
              <input type="text" name="username" id="id_username" autofocus="autofocus"/>
              <label for="username">아이디</label>
            </div>
            <div class="input-area">
              <input type="password" name="password" id="id_password"/>
              <label for="password">비밀번호</label>
            </div>
            <button type="submit" class="btn">로그인</button>
          </form>

          <div class="link-area">
            <a href="{% url 'social:begin' 'google-oauth2' %}" class='btn'>
              <i class="bi bi-google"></i>
              Login
            </a>
            <a href="{% url 'accounts:signup' %}">회원가입</a>
          </div>
        </div>
      </div>
    </div>

  </body>

</html>