pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import logout

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("todos/", include("todos.urls")),
    path("accounts/", include("accounts.urls")),
    path("studies/", include("studies.urls")),
    path("social/", include("social_django.urls", namespace="social")),
    path("chat/", include("chat.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studies/urls.py
from django.urls import path
from . import views

app_name = "studies"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("create_todos/<int:study_pk>", views.create_todos, name="create_todos"),
    path(
        "detail/<int:study_pk>/<int:management_pk>",
        views.delete_todos,
        name="delete_todos",
    ),
    path("detail/<int:study_pk>", views.detail, name="detail"),
    path("detail/<int:study_pk>/delete", views.delete, name="delete"),
    path("detail/<int:study_pk>/update", views.update, name="update"),
    path("info/<int:study_pk>", views.info, name="info"),
    path("detail/<int:study_pk>/join", views.join, name="join"),
    path("detail/<int:study_pk>/<int:user_pk>/refusal", views.refusal, name="refusal"),
    path(
        "detail/<int:study_pk>/<int:user_pk>/accept_and_drive_out",
        views.accept_and_drive_out,
        name="accept_and_drive_out",
    ),
]

todos/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path("today/", views.today, name="today"),
    path("create/", views.create, name="create"),
    path("delete/<int:todos_pk>", views.delete, name="delete"),
    path("week/", views.week, name="week"),
    path("week/<str:few_week>", views.week_asyn, name="week_asyn"),
    path("read_all", views.read_all, name="read_all"),
    path("update/<int:pk>", views.update, name="update"),
    path("is_completed/", views.is_completed, name="is_completed"),
    path("detail_asyn/", views.detail_asyn, name="detail_asyn"),
]

todos/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Todos(models.Model):
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    content = models.TextField()
    when = models.DateField()
    started_at = models.CharField(max_length=5, null=True)
    expired_at = models.CharField(max_length=5, null=True)
    is_completed = models.BooleanField(default=False)


class Tag(models.Model):
    todo = models.ForeignKey("Todos", on_delete=models.CASCADE, related_name="tagged")
    content = models.CharField(max_length=30)

todos/forms.py
from .models import Todos
from django import forms


class TodosForm(forms.ModelForm):
    class Meta:
        model = Todos
        fields = [
            "title",
            "content",
        ]

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model as User
from .forms import TodosForm
from .models import Todos, Tag
from datetime import datetime, timedelta
from django.contrib import messages
from function import change_value, create_tag, check_time
from django.http import JsonResponse
from django.core import serializers
import json
from accounts.decorator import login_message_required
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from studies.models import StudyTodos
from dateutil.relativedelta import relativedelta

# Create your views here.
@login_message_required
def today(request):

    today = str(datetime.now())[:10]

    # 로그인 유저의 today todos 찾기
    today_todos = Todos.objects.filter(user_id=request.user, when=today).order_by(
        "started_at"
    )

    # timetable 넘겨주기 위해 & 태그 보여주기 위해
    time_list = []
    tag_list = []

    for todo in today_todos:
        if todo.started_at != "" and todo.expired_at != "":
            start = change_value(todo.started_at)
            end = change_value(todo.expired_at)
            time = end - start

            time_list.append([])
            time_list[-1].append(start)
            time_list[-1].append(time)

        # 업데이트 화면 태크 보여주기
        today_tag = Todos.objects.get(pk=todo.pk).tagged.all()
        if today_tag:
            tag_json = serializers.serialize("json", today_tag)
            tag_list.append(tag_json)
        else:
            tag_list.append("")

    # 비동기 보여주기 (업데이트)
    if request.method == "POST":
        res_json = serializers.serialize(
            "json",
            Todos.objects.filter(user_id=request.user, when=today).order_by(
                "started_at"
            ),
        )
        return JsonResponse({"resJson": res_json, "resJson2": tag_list})

    # 오늘 해야 하는 스터디 todos
    today_study_todos = StudyTodos.objects.filter(
        user_id=request.user, start__lte=today, end__gte=today
    )

    # 달성율
    if len(today_todos) != 0:
        achievement_rate = round(
            100 * (today_todos.filter(is_completed=True).count() / len(today_todos))
        )
    else:
        achievement_rate = 0

    todosForm = TodosForm()

    context = {
        "time_list": time_list,
        "today_todos": today_todos,
        "todosForm": todosForm,
        "achievement_rate": achievement_rate,
        "today_study_todos": today_study_todos,
    }
    return render(request, "todos/complete/today_main.html", context)


@login_message_required
def create(request):
    if request.method == "POST":
        start, end, tags = (
            request.POST.get("started_at"),
            request.POST.get("expired_at"),
            request.POST.get("tags"),
        )
        todoForm = TodosForm(request.POST)

        # timetable 체크 및 중복되면 저장 x
        user = request.user
        today = str(datetime.now())[:10]
        today_todos = Todos.objects.filter(user_id=request.user, when=today)

        # 시간 입력이 잘못되었을때
        if check_time(request, today_todos, start, end, messages) == False:
            return redirect("todos:today")

        if todoForm.is_valid():
            todo = todoForm.save(commit=False)
            todo.user_id, todo.when, todo.started_at, todo.expired_at = (
                user,
                today,
                start,
                end,
            )
            todo.save()

            # tag create
            create_tag(tags, Tag, todo)

        return redirect("todos:today")
    else:
        messages.warning(request, "잘못된 접근입니다.")
        return redirect("todos:today")


@login_message_required
def delete(request, todos_pk):
    today = str(datetime.now())[:10]

    if request.method == "POST":
        todo = Todos.objects.get(pk=todos_pk)
        todo.delete()
        res_json = serializers.serialize(
            "json",
            Todos.objects.filter(user_id=request.user, when=today).order_by(
                "started_at"
            ),
        )
        return JsonResponse({"resJson": res_json})
    res_json = serializers.serialize(
        "json",
        Todos.objects.filter(user_id=request.user, when=today).order_by("started_at"),
    )
    return JsonResponse({"resJson": res_json})


@login_message_required
def update(request, pk):
    todo = get_object_or_404(Todos, pk=pk)
    today = str(datetime.now())[:10]

    if request.method == "POST":
        todoForm = TodosForm(request.POST, instance=todo)
        start, end, tags = (
            request.POST.get("started_at"),
            request.POST.get("expired_at"),
            request.POST.get("tags"),
        )

        user = request.user

        # 시간은 수정 기능 막아둬서 주석 처리함

        # 시간 입력이 잘못되었을때
        # if check_time(request, today_todos, start, end, messages) == False:
        #     return redirect("todos:today")

        if todoForm.is_valid():
            todo = todoForm.save(commit=False)
            todo.user_id, todo.when, todo.started_at, todo.expired_at = (
                user,
                today,
                start,
                end,
            )
            todo.save()

            # 태그 업데이트 => 삭제 후 다시 생성
            todo_tags = Tag.objects.filter(todo=pk)
            for todo_tag in todo_tags:
                todo_tag.delete()
            create_tag(tags, Tag, todo)

        # 해당 투두에 태그가 있을 때 json으로 보냄
        todo_tags = Tag.objects.filter(todo=pk)
        if todo_tags:
            tag_json = serializers.serialize("json", todo_tags.order_by("id"))
        else:
            tag_json = ""

        context = {
            "todoTitle": todo.title,
            "todoCont": todo.content,
            "tagJson": tag_json,
        }
        return JsonResponse(context)

    else:
        todoForm = TodosForm(instance=todo)
        context = {
            "todoForm": todoForm,
        }
        return JsonResponse(context)


@login_required
def week(request):
    # 오늘 날짜 기준 정렬
    few_week = 0
    today = datetime.today().weekday() + 1
    now = datetime.now()
    week = now + timedelta(weeks=few_week, days=-(today % 7))

    time_list = []
    for i in range(7):
        temp = week + timedelta(days=i)
        temp_time = temp.strftime("%Y-%m-%d")
        time_list.append(Todos.objects.filter(when=temp_time, user_id=request.user))
    todos = TodosForm()
    context = {
        "todos": todos,
        "time_list": time_list,
    }
    return render(request, "todos/complete/week_todos.html", context)


@login_required
def week_asyn(request, few_week):
    few_week = int(few_week)
    today = datetime.today().weekday() + 1
    now = datetime.now()
    week = now + timedelta(weeks=few_week, days=-(today % 7))

    time_list = []
    res = []
    for i in range(7):
        temp = week + timedelta(days=i)
        temp_time = temp.strftime("%Y-%m-%d")
        time_list.append(Todos.objects.filter(when=temp_time, user_id=request.user))
        # 비동기
        res_json = serializers.serialize(
            "json", Todos.objects.filter(when=temp_time, user_id=request.user)
        )
        res.append(res_json)

    # todos = TodosForm()
    if request.method == "GET":
        return JsonResponse({"resJson": res})


@login_required
def read_all(request):
    # 값 보내기 위한 알고리즘(past, present, future)
    now = datetime.now()
    today = str(now)[:10]
    yesterday = str(now - timedelta(1))[:10]
    # print(str(yesterday)[:10])
    # 과거
    # months=1을 통하여 월별 관리, 모든 과거: lte
    few_month_ago = str(now - relativedelta(months=1))[:10]
    past_data = Todos.objects.filter(
        user_id=request.user, when__range=(few_month_ago, yesterday)
    ).order_by("-when")

    # 각 데이터에서 when 필드를 문자열로 추출해서 중복을 제거함
    # 각 날짜를 키를 하는 딕셔너리를 생성
    past_date = set(map(lambda x: x.when.strftime("%Y-%m-%d"), past_data))
    past = dict.fromkeys(past_date)

    # 각 데이터의 날짜를 문자열로 만들고
    # 해당 날짜를 키로써 접근한 것이 None 이면 빈 리스트 생성
    # 생성 후 해당 리스트에 날짜에 맞는 데이터가 쌓임
    for i in past_data:
        date = i.when.strftime("%Y-%m-%d")

        if not past[date]:
            past[date] = []

        temp = past[date]
        temp.append(i)

    past = dict(sorted(past.items(), reverse=True))

    # 현재
    present = Todos.objects.filter(user_id=request.user, when=today)
    # 미래
    tomorrow = str(now + timedelta(days=1))[:10]
    future = Todos.objects.filter(user_id=request.user, when__gte=tomorrow).order_by(
        "when"
    )

    context = {
        "past": past,
        "present": present,
        "future": future,
    }
    return render(request, "todos/complete/all_todos.html", context)


# checkbox 비동기
@require_POST
def is_completed(request):
    if request.method == "POST":
        # JSON 데이터 받음
        data = json.loads(request.body)

        # 변경된 값이랑 어떤 todo 인지 특정할 수 있는 id 값
        is_completed = data.get("is_completed")
        todoId = data.get("todoId")

        # 해당 id 값으로 todo 객체를 가져옴
        obj = Todos.objects.get(id=todoId)

        # 받아온 값으로 변경
        obj.is_completed = is_completed
        obj.save()

        # 변경된 값으로 응답
        context = {"is_completed": is_completed}

        return JsonResponse(context)


@login_required
def detail_asyn(request):
    pk = request.GET.get("todoIdValue")

    todo = Todos.objects.filter(id=pk)

    context = {"todo": serializers.serialize("json", todo)}

    return JsonResponse(context)

templates/todos/complete/today_main.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="container" id="today">
  <div class="lnb-area">
    <div class="lnb">
      <input type="radio" name="tabmenu" id="tab1" class="tabs">
      <label for="tab1" class="tab">
        <a href="{% url 'todos:week' %}">WEEK</a>
      </label>
      <input type="radio" name="tabmenu" id="tab2" class="tabs" checked="checked">
      <label for="tab2" class="tab">
        <a href="{% url 'todos:today' %}">TODAY</a>
      </label>
      <input type="radio" name="tabmenu" id="tab3" class="tabs">
      <label for="tab3" class="tab">
        <a href="{% url 'todos:read_all' %}">ALL</a>
      </label>
      <span class="glider"></span>
    </div>
  </div>

  <div class="box">
    <div class="today-info">
      <div class="today-date">
        <p class="today-date-month">
          M
        </p>
        <p class="today-date-day">D</p>
      </div>
      <div class="today-progress">
        <div class="mkCharts" data-percent="{{achievement_rate}}" data-color="#3cddaa" data-size="100" data-stroke="3">
        </div>
        <!-- <canvas id="today-progress-crc" width="100" height="100"></canvas>
        <div id="progress-per" data-ach-rate="{{achievement_rate}}">0%</div>
       -->
      </div>
    </div>
    <div class="today-task-add">
      <button class="icon-btn add-btn">
        <div class="add-icon"></div>
        <div class="btn-txt">할 일 추가하기</div>
      </button>
    </div>

    <section class="today-section">
      <div class="today-task-add-spec">
        <!-- today todo Form -->
        <form action="{% url 'todos:create' %}" method="post" id="today-form" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="date" name="when" id="id_when">
          <input type="text" name="title" placeholder="할일 추가하기" class="today_task-title">
          <div class="timepicker-area">
            <div class="starttime-select">
              <label for="starttime-pick">시작 시간</label>
              <input type="text" id="starttime-pick" value="" name="started_at" class="time-pickable"
                readonly="readonly">
            </div>
            <span class="time-tilder">~</span>
            <div class="endtime-select">
              <label for="endtime-pick">종료 시간</label>
              <input type="text" id="endtime-pick" value="" name="expired_at" class="time-pickable" readonly="readonly">
            </div>
          </div>
          <textarea name="content" class="today_task-textarea" id="id_content" cols="30" rows="10"
            placeholder="할 일 상세"></textarea>
          <div class="keyword-box">
            <input type="text" name="tags" id="" placeholder="#keyword">
          </div>
          <div class="btn-area">
            <button type="submit" class="btn">할일 추가</button>
          </div>
        </form>
      </div>
    </section>
  </div>

  <div class="box-area">
    <div class="box today-task-area">
      <ul class="today-task-list">
        {% for todo in today_todos %}
        <li class="task" data-todo-pk="{{todo.pk}}">
          <p class="task-cont">{{ todo.title }}</p>
          {% if todo.is_completed %}
          <input type="checkbox" name="task-chb{{todo.pk}}" id="task-chb{{todo.pk}}" checked="checked">
          {% else %}
          <input type="checkbox" name="task-chb{{todo.pk}}" id="task-chb{{todo.pk}}">
          {% endif %}
          <label for="task-chb{{todo.pk}}" class="task-chb"></label>
        </li>
        {%empty%}
        <li class="task task-empty">
          <p class="task-cont ">
            아직 작성된 할일이 없어요 :(</p>
        </li>
        {% endfor %}
      </ul>

      <div class="today-timetable">
        <div class="timetable-hour hour-left"></div>
        <div class="timetable-box timetable-left"></div>
        <div class="timetable-hour hour-right"></div>
        <div class="timetable-box timetable-right"></div>
      </div>
    </div>

    <div class="box today-section" id="task-detail">
      <div class="today-task-view-spec">
        <form action="" method="post" id="today-detail-form" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="date" name="when">
          <input type="text" name="title" class="today_task-title" id="detail-title">
          <div class="timepicker-area">
            <div class="starttime-select-edit">
              <label for="starttime-pick-edit">시작 시간</label>
              <input type="text" id="starttime-pick-edit" value="" name="started_at" class="time-pickable"
                readonly="readonly">
            </div>
            <span class="time-tilder">~</span>
            <div class="endtime-select-edit">
              <label for="endtime-pick-edit">종료 시간</label>
              <input type="text" id="endtime-pick-edit" value="" name="expired_at" class="time-pickable"
                readonly="readonly">
            </div>
          </div>
          <textarea name="content" class="today_task-textarea" id="detail-cont" cols="30" rows="10"></textarea>
          <!-- <fieldset class="today-task-fileadd"> <legend>Image/File</legend> <label for="today-task-imgfile"> <div class="loaded-file"></div> <div class="upload-none"> <span class="attach_img-icon material-symbols-outlined">imagesmode</span> 사진/파일을 첨부하세요 </div> </label> <input type="file" name="todoimg" class="today_task-img" id="today-task-imgfile"> </fieldset> -->
          <div class="keyword-box">
            <input type="text" name="tags" id="detail-tag" placeholder="#keyword">
          </div>
          <div class="btn-area">
            <button class="btn" id="todo-update">할일 수정</button>
        </form>
        <form action="" method="post" id="detail-del-form">
          {% csrf_token %}
          <button type="submit" class="btn-del material-symbols-outlined" id="detail-btn-del">
            delete_forever
          </button>
        </form>
      </div>

    </div>

  </div>

  <!-- today-study-area -->
  <div class="box today-study-area">
    <span class="open-icon material-symbols-outlined">
      arrow_back_ios_new
    </span>
    <div class="study-tasklist-area">
      <h3 class="tit">Study</h3>
      <ul class="study-task-list">
        {% for study_todo in today_study_todos %}
        <li class="task">
          <a href="{% url 'studies:detail' study_todo.study_pk.pk %}">
            <div>
              <p style="padding: 5px 0px;">{{study_todo.title}}</p>
              <div style="text-align: right;">
                <p style="display:inline-block; padding: 7px 12px; border-radius: 10px;">
                  {{ study_todo.study_pk.title}}
                </p>
              </div>
            </div>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="time-test">
    {% for time in time_list %}
    <p class="testbox" data-time-array="{{time}}">{{time}}</p>
    {% endfor %}
  </div>
</div>

</div>
</div>

<script>
  const timePickerArea = document.querySelector('.timepicker-area');

  function activate() {

    document
      .querySelectorAll(".time-pickable")
      .forEach(timePickable => {
        let activePicker = null;
        timePickable.addEventListener("focus", () => {
          if (activePicker)
            return;

          activePicker = show(timePickable);

          const onClickAway = ({ target }) => {
            if (target === activePicker || target === timePickable || activePicker.contains(target)) {
              return;
            }

            document.removeEventListener("mousedown", onClickAway);
            timePickerArea.removeChild(activePicker);
            activePicker = null;
          };

          document.addEventListener("mousedown", onClickAway);
        });
      });
  }

  function show(timePickable) {
    const picker = buildPicker(timePickable);
    // const { bottom: top, left } = timePickable.getBoundingClientRect();
    console.log(this);
    timePickerArea.appendChild(picker);

    // picker.style.top = `${top}px`;
    // picker.style.left = `${left}px`;

    // timePickerArea.appendChild(picker);

    return picker;
  }

  function buildPicker(timePickable) {

    // const todayFormArea = document.querySelector('.today-task-add-spec');

    const picker = document.createElement("div");
    // timePickerArea.appendChild(picker);

    const hourOptions = [
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24
    ].map(numberToOption);
    const minuteOptions = [
      0,
      10,
      20,
      30,
      40,
      50
    ].map(numberToOption);

    picker
      .classList
      .add("time-picker");
    picker.innerHTML = `  
          <select class="time-picker__select">
              ${hourOptions.join("")}
          </select>
          :
          <select class="time-picker__select">
              ${minuteOptions.join("")}
          </select>
      `;

    // console.log(timePickerArea);
    // timePickerArea.insertAdjacentHTML("beforeend", `
    //       <div class="time-picker">
    //         <select class="time-picker__select">
    //           ${hourOptions.join("")}
    //       </select>
    //       :
    //       <select class="time-picker__select">
    //           ${minuteOptions.join("")}
    //       </select>
    //       </div>
    // `)

    const selects = getSelectsFromPicker(picker);

    selects
      .hour
      .addEventListener("change", () => timePickable.value = getTimeStringFromPicker(picker));
    selects
      .minute
      .addEventListener("change", () => timePickable.value = getTimeStringFromPicker(picker));

    if (timePickable.value) {
      const { hour, minute, meridiem } = getTimePartsFromPickable(timePickable);

      selects.hour.value = hour;
      selects.minute.value = minute;
    }

    return picker;
  }

  function getTimePartsFromPickable(timePickable) {
    const pattern = /^(\d+):(\d+) (am|pm)$/;
    const [hour, minute] = Array
      .from(timePickable.value.match(pattern))
      .splice(1);

    return { hour, minute };
  }

  function getSelectsFromPicker(timePicker) {
    const [hour, minute] = timePicker.querySelectorAll(".time-picker__select");

    return { hour, minute };
  }

  function getTimeStringFromPicker(timePicker) {
    const selects = getSelectsFromPicker(timePicker);

    return `${selects.hour.value}:${selects.minute.value}`;
  }

  function numberToOption(number) {
    const padded = number
      .toString()
      .padStart(2, "0");

    return `<option value="${padded}">${padded}</option>`;
  }

  activate();

  // <!-- study todo div -->

  const studyArea = document.querySelector('.today-study-area');
  const openStudyArea = document.querySelector('.study-tasklist-area');
  const openIcon = document.querySelector('.open-icon');
  const taskArea = document.querySelector('.today-task-area');
  const studyText = document.querySelector('.today-study-area .tit');


  studyArea.addEventListener('click', () => {
    studyArea.classList.toggle('activate');
    openStudyArea.classList.toggle('activate');
    taskArea.classList.toggle('activate');
    openIcon.classList.toggle('activate');
    studyText.classList.toggle('activate');

    /* if (openStudyArea.style.display === "none") {
      studyArea.style.width = "30%";
      studyArea.style.justifyContent = "space-between";
      openStudyArea.style.display = "block";
      openStudyArea.style.width = "380px";
      openStudyArea.style.alignSelf = "start";
      openIcon.style.transform = "rotate(180deg)";
      // taskArea.style.width = "80%";
      taskArea.style.transition = "0.8s ease";
    } else {
      openStudyArea.style.display = "none";
      openIcon.style.transform = "rotate(-360deg)";
      // taskArea.style.width = "80%";
      studyArea.style.transition = "0.8s ease";
      studyArea.style.justifyContent = "center";
      studyArea.style.width = "5%";
      studyArea.style.display = "flex";
    } */
  });
</script>
<script>
  message = document.querySelectorAll('.message-button')
  console.log(message)
  message.forEach(function (v, i, o) {
    v.addEventListener('click', event => {
      v.parentElement.remove()
    })
  })
</script>
{% endblock body %}

templates/todos/complete/week_todos.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container" id="week">
  <div class="lnb-area">
    <div class="lnb">
      <input type="radio" name="tabmenu" id="tab1" class="tabs" checked>
      <label for="tab1" class="tab">
        <a href="{% url 'todos:week' %}">WEEK</a>
      </label>
      <input type="radio" name="tabmenu" id="tab2" class="tabs">
      <label for="tab2" class="tab">
        <a href="{% url 'todos:today' %}">TODAY</a>
      </label>
      <input type="radio" name="tabmenu" id="tab3" class="tabs">
      <label for="tab3" class="tab">
        <a href="{% url 'todos:read_all' %}">ALL</a>
      </label>
      <span class="glider"></span>
    </div>
    <div class="week-btn-area">
      <a href="" class="week-btn" data-is-prev="true" data-week-cnt="-1">
        <span class="material-symbols-outlined  week-btn-prev">
          arrow_back_ios
        </span>
        <span class="prev-week">prev</span>
      </a>
      <a href="" class="week-btn" data-is-prev="false" data-week-cnt="1">
        <span class="next-week">next</span>
        <span class="material-symbols-outlined week-btn-next">
          arrow_forward_ios
        </span>
      </a>
    </div>
  </div>
  <div class="box-area week-area">

    {% for todo_list in time_list %}
    <div class="box">
      <h3 class="tit shd weekday">weekday
      </h3>
      <ul class="task-list">
        {% for todo in todo_list %}
        <li class="task">
          <p class="task-cont">{{todo.title}}</p>
          {% if todo.is_completed %}
          <input type="checkbox" name="task-chb{{ todo.id }}" id="task-chb{{ todo.id }}" checked="checked">
          {% else %}
          <input type="checkbox" name="task-chb{{ todo.id }}" id="task-chb{{ todo.id }}">
          {% endif %}
          <label for="task-chb{{ todo.id }}" class="task-chb"></label>
        </li>
        {%empty%}
        <li class="task task-empty">
          <p class="task-cont"> 작성된 할일이 없어요 :(</p>
        </li>
        {% endfor %}
      </ul>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock body %}